"""empty message

Revision ID: d6de87ebc5c3
Revises: 0611429b9b2c
Create Date: 2023-03-28 17:13:58.592017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6de87ebc5c3'
down_revision = '0611429b9b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=140), nullable=False),
    sa.Column('dtlancamento', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], name=op.f('fk_lancamentos_conta_id_contas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lancamentos_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lancamentos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos')
    # ### end Alembic commands ###
